---
name: parallel
version: '1.20'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: d1878f12ad72384ea2c13b6089984db6b0fe0715
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
